### ISSUE TITLE
Obtaining variable value at minima

### ISSUE THREAD

**Issue by go-pujan** [baopng/NSGA-II#1]
Hello!

Please can I know how to obtain the value of the variables where the minima is found in your implementation.

Thanks

**Comment by baopng** [comment]
Hi!

Thank you for concerning about our project. Maybe I got your idea wrong but there is no true minima in multi-objective problem, which our implementation is dealing with. Let's say, there is hardly a variable yielding both minimal values of f1 and f2 function. The "evolve" method indeed returns a list of the best individuals (variables). If you want to pick one of them, I suggest taking a look at your problem again. For example, you really want to minimize f1 and just need f2 smaller than a threshold, then, there you go. Also, if your problem indeed has a true minima, the list should contains only one element. 

I hope this answer help. Feel free to contact us if you have further questions.
