### ISSUE TITLE
Ask for help-three-dimensional picture

### ISSUE THREAD

**Issue by TeerLu** [baopng/NSGA-II#10]
Hello how could I get the Viennet picture(**three-dimensional picture**)? I couldn't find the related code in your code, but I could find kur and sch.  Many thanks!

**Comment by baopng** [comment]
Unfortunately I only attached the image output of the Viennet problem as example. I believe you can reproduce the code just fine using the information from this [link](https://en.wikipedia.org/wiki/Test_functions_for_optimization) and my other examples.

**Comment by TeerLu** [comment]
Got it! Many thanks for your message!

**Comment by baopng** [comment]
Glad I could help 😀 
I will now close this issue
