### ISSUE TITLE
how to get individuals in the last generation?

### ISSUE THREAD

**Issue by cubewatermelon** [baopng/NSGA-II#4]
Hi, thanks for your wonderful work! During the use, I want to know the input values of the problems in the last generation, the x in the example. How can I get these individuals? Thanks!

**Comment by baopng** [comment]
Hi! Glad that we could help :) 
The `evolve` method return a list of `Individual` `i`, you can call `i.features` to get `x`, just as i called `i.objectives` to get `y` in the example.
Cheer.

**Comment by cubewatermelon** [comment]
Thanks! That helps a lot! :)
